# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 04:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tagcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=30, verbose_name='Numero de TAG')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='fecha de alta')),
            ],
            options={
                'verbose_name_plural': 'TAG',
            },
        ),
        migrations.CreateModel(
            name='Tagcompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Compa\xf1ia del TAG')),
            ],
            options={
                'verbose_name_plural': 'Compa\xf1ia TAG',
            },
        ),
        migrations.AddField(
            model_name='tagcard',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tagcompany', to='traveltag.Tagcompany', verbose_name='Compa\xf1ia del TAG'),
        ),
    ]
