# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 04:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveltag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagcompany',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='fecha de alta'),
        ),
    ]
