# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 00:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='cover_type',
            field=models.CharField(choices=[('0', 'N/A'), ('1', 'Amplia'), ('2', 'Limitada'), ('3', 'Da\xf1os a terceros')], default=0, max_length=1, verbose_name='Tipo de cobertura'),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de alta'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Compa\xf1ia'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='insurances.Company', verbose_name='Compa\xf1ia Aseguradora'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de alta'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='end_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fin vigencia'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='reference',
            field=models.CharField(max_length=30, verbose_name='Numero de poliza'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='start_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Inicio de vigencia'),
        ),
    ]
