# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 01:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0003_auto_20170103_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='fecha de alta'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, verbose_name='compa\xf1ia'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='insurances.Company', verbose_name='compa\xf1ia aseguradora'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='cover_amount',
            field=models.FloatField(default=0, verbose_name='importe de la coberura'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='cover_type',
            field=models.CharField(choices=[('0', 'N/A'), ('1', 'Amplia'), ('2', 'Limitada'), ('3', 'Da\xf1os a terceros')], default=0, max_length=1, verbose_name='tipo de cobertura'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='fecha de alta'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='end_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='fin vigencia'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='reference',
            field=models.CharField(max_length=30, verbose_name='numero de poliza'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='start_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='inicio de vigencia'),
        ),
    ]
