# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0004_auto_20170103_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='phone',
            field=models.CharField(default='', help_text='Indica el n\xfamero para llamar en caso de un sinisetro', max_length=50, verbose_name='numero de la aseguradora'),
        ),
    ]
