# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0005_policy_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='ultima modificacion'),
        ),
        migrations.AddField(
            model_name='policy',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='ultima modificacion'),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de alta'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de alta'),
        ),
    ]
