# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0006_auto_20170112_0350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='cover_amount',
        ),
        migrations.AddField(
            model_name='policy',
            name='cover_damage',
            field=models.FloatField(default=0, verbose_name='cobertura da\xf1os materiales'),
        ),
        migrations.AddField(
            model_name='policy',
            name='cover_medic_expense',
            field=models.FloatField(default=0, verbose_name='cobertura medica'),
        ),
        migrations.AddField(
            model_name='policy',
            name='cover_robbery',
            field=models.FloatField(default=0, verbose_name='cobertura robo'),
        ),
        migrations.AddField(
            model_name='policy',
            name='cover_total',
            field=models.FloatField(default=0, verbose_name='cobertura total'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='cover_type',
            field=models.CharField(choices=[('0', 'N/A'), ('Amplia', 'Amplia'), ('Limitada', 'Limitada'), ('Da\xf1os a terceros', 'Da\xf1os a terceros')], default=0, max_length=1, verbose_name='tipo de cobertura'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='phone',
            field=models.CharField(default='', help_text='Indica el n\xfamero para llamar en caso de un sinisetro,solo numeros', max_length=10, verbose_name='numero de la aseguradora'),
        ),
    ]
