# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0007_auto_20170112_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='phone',
            field=models.CharField(default='', help_text='Indica el n\xfamero para llamar en caso de un sinisetro, solo numeros', max_length=10, verbose_name='numero de la aseguradora'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='price',
            field=models.FloatField(default=0, help_text='cuanto costo el seguro', verbose_name='costo del seguro'),
        ),
    ]
