# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0008_auto_20170112_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='cover_type',
            field=models.CharField(choices=[('0', 'N/A'), ('Amplia', 'Amplia'), ('Limitada', 'Limitada'), ('Da\xf1os a terceros', 'Da\xf1os a terceros')], default=0, max_length=20, verbose_name='tipo de cobertura'),
        ),
    ]
