# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0009_auto_20170112_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='price',
            field=models.FloatField(default=0, help_text='costo el seguro', verbose_name='costo del seguro'),
        ),
    ]
