# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0010_auto_20170112_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='cover_damage',
            field=models.TextField(default=0, max_length=50, verbose_name='cobertura da\xf1os materiales'),
        ),
    ]
