# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0011_auto_20170116_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='cover_damage',
            field=models.CharField(default='', max_length=250, verbose_name='cobertura da\xf1os materiales'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='cover_medic_expense',
            field=models.CharField(default='', max_length=250, verbose_name='cobertura medica'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='cover_robbery',
            field=models.CharField(default='', max_length=250, verbose_name='cobertura robo'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='cover_total',
            field=models.CharField(default='', max_length=250, verbose_name='cobertura total'),
        ),
    ]
