# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-03 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0012_auto_20170116_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='image',
            field=models.ImageField(default='', upload_to='insurances/', verbose_name='foto poliza:'),
        ),
    ]
