# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paymentcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='nombre')),
                ('card_type', models.CharField(choices=[('Tarjeta de Gasolina', 'Tarjeta de Gasolina'), ('Tarjeta de Credito', 'Tarjeta de Credito')], default='', max_length=20, verbose_name='tipo de tarjeta')),
                ('card_number', models.CharField(default=0, max_length=20, verbose_name='numero de tarjeta')),
                ('card_limit', models.FloatField(default=0, verbose_name='limite de credito')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de alta')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='ultima modificacion')),
            ],
            options={
                'verbose_name_plural': 'Tarjeta de Gastos',
            },
        ),
    ]
