# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 00:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0015_auto_20170116_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasexpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odo', models.FloatField(default=0, verbose_name='kilometraje al momento de la carga')),
                ('odo_picture', models.ImageField(default='', upload_to='expense/gas_odo/', verbose_name='foto del ticket')),
                ('gas_price', models.FloatField(default=0, verbose_name='precio x litro')),
                ('gas_liters', models.FloatField(default=0, verbose_name='litros cargados')),
                ('gas_total', models.FloatField(default=0, verbose_name='importe en pesos')),
                ('ticket_picture', models.ImageField(default='', upload_to='expense/gas_ticket/', verbose_name='foto del ticket')),
                ('date_load', models.DateTimeField(default=datetime.datetime.now, verbose_name='fecha de carga')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de alta')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='ultima modificacion')),
                ('vehicleassigment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicleassigment', to='vehicle.VehicleAssigment', verbose_name='vehiculo asignado')),
            ],
            options={
                'ordering': ['date_load', 'vehicleassigment'],
                'verbose_name_plural': 'gastos gasolina',
            },
        ),
    ]
