# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasexpense',
            name='odo_picture',
            field=models.ImageField(default='', upload_to='expense/gas_odo/', verbose_name='foto de odometro'),
        ),
        migrations.AlterField(
            model_name='gasexpense',
            name='ticket_picture',
            field=models.ImageField(blank=True, default='', upload_to='expense/gas_ticket/', verbose_name='foto del ticket'),
        ),
    ]
