# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20170118_0059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gasexpense',
            options={'ordering': ['date_load', 'vehicleassigment'], 'verbose_name_plural': 'gastos de gasolina'},
        ),
        migrations.AddField(
            model_name='gasexpense',
            name='fuel_type',
            field=models.CharField(choices=[('0', 'Selecciona el tipo de gasolina'), ('Magna', 'Magna'), ('Premium', 'Premium'), ('Disel', 'Disel')], default='', max_length=7, verbose_name='tipo de combustible'),
        ),
    ]
