# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-26 02:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_gascardusage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gascardusage',
            old_name='serial_number',
            new_name='vehicle_serial_number',
        ),
    ]
