# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-13 05:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UberData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(default='', max_length=200)),
                ('phone_number', models.CharField(default='', max_length=11)),
                ('email', models.EmailField(default='', max_length=254)),
                ('trip_type', models.CharField(choices=[('Trip', 'Trip'), ('Misc Payment', 'Misc Payment')], default='', max_length=200)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('description', models.TextField(blank=True, default='', max_length=200)),
                ('trip_number', models.CharField(default='', max_length=40, unique=True)),
                ('fare', models.FloatField(default=0)),
                ('surge', models.FloatField(blank=True, default=0)),
                ('toll', models.FloatField(blank=True, default=0)),
                ('misc', models.FloatField(blank=True, default=0)),
                ('other', models.FloatField(blank=True, default=0)),
                ('meter_rate', models.FloatField(blank=True, default=0)),
                ('gratuity', models.FloatField(blank=True, default=0)),
                ('commission', models.FloatField(default=0)),
                ('tax_on_fee', models.FloatField(blank=True, default=0)),
                ('total_payment', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['date'],
                'verbose_name_plural': 'Uber Data',
            },
        ),
    ]
