# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0002_auto_20170113_0510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uberdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='uberdata',
            name='trip_number',
            field=models.CharField(default='', max_length=40, primary_key=True, serialize=False, unique=True),
        ),
    ]
