# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-10 03:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0003_auto_20170120_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggUberData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(default='', max_length=200)),
                ('phone_number', models.CharField(default='', max_length=11)),
                ('email', models.EmailField(default='', max_length=254)),
                ('trip_type', models.CharField(choices=[('Trip', 'Trip'), ('Misc Payment', 'Misc Payment')], default='', max_length=200)),
                ('trip_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('trip_year', models.IntegerField(blank=True, default=0)),
                ('trip_month', models.IntegerField(blank=True, default=0)),
                ('trip_day', models.IntegerField(blank=True, default=0)),
                ('week', models.IntegerField(blank=True, default=0)),
                ('quarter', models.IntegerField(blank=True, default=0)),
                ('description', models.TextField(blank=True, default='', max_length=200)),
                ('viajes', models.IntegerField(default=0)),
                ('fare', models.FloatField(blank=True, default=0)),
                ('surge', models.FloatField(blank=True, default=0)),
                ('toll', models.FloatField(blank=True, default=0)),
                ('misc', models.FloatField(blank=True, default=0)),
                ('other', models.FloatField(blank=True, default=0)),
                ('meter_rate', models.FloatField(blank=True, default=0)),
                ('gratuity', models.FloatField(blank=True, default=0)),
                ('commission', models.FloatField(blank=True, default=0)),
                ('tax_on_fee', models.FloatField(blank=True, default=0)),
                ('total_payment', models.FloatField(blank=True, default=0)),
            ],
            options={
                'ordering': ['trip_date'],
                'verbose_name_plural': 'Aggregated Uber Data',
            },
        ),
    ]
