# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-11 02:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0005_auto_20170210_0337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uberdataagg',
            options={'managed': False, 'ordering': ['trip_date'], 'verbose_name_plural': 'Aggregated Uber Data'},
        ),
    ]
