# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-25 04:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0012_auto_20170425_0407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploaduberdata',
            old_name='fiel_procesed',
            new_name='file_procesed',
        ),
    ]
