# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-26 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0013_auto_20170425_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaduberdata',
            name='uber_file_uploaded',
            field=models.FileField(blank=True, default='', upload_to='uber/uberfiles', verbose_name='archivo de datos de uber'),
        ),
    ]
