# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-26 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0015_auto_20170426_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaduberdata',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='nombre de la carga'),
        ),
    ]
