# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-27 04:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0016_auto_20170426_0106'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vmycarsincomebyyearmonth',
            table='vmycarsincomebyyearmonth',
        ),
    ]
