# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-23 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0017_auto_20170427_0434'),
    ]

    operations = [
        migrations.CreateModel(
            name='VMyCarsIncomeByDriverYearMonthWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=10)),
                ('year', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=0)),
                ('week', models.IntegerField(default=0)),
                ('quarter', models.IntegerField(default=0)),
                ('phone_number', models.CharField(default=0, max_length=12)),
                ('viajes', models.IntegerField(default=0)),
                ('fare', models.FloatField(default=0)),
                ('surge', models.FloatField(default=0)),
                ('toll', models.FloatField(default=0)),
                ('misc', models.FloatField(default=0)),
                ('other', models.FloatField(default=0)),
                ('meter_rate', models.FloatField(default=0)),
                ('gratuity', models.FloatField(default=0)),
                ('commission', models.FloatField(default=0)),
                ('tax_on_fee', models.FloatField(default=0)),
                ('total_payment', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['phone_number'],
                'db_table': 'vmycarsincomebydriverdayyear',
                'managed': False,
                'verbose_name_plural': 'Uber Driver Data',
            },
        ),
    ]
