# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-23 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0018_vmycarsincomebydriveryearmonthweek'),
    ]

    operations = [
        migrations.CreateModel(
            name='VMycarsFilterDriverMonthYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default=0, max_length=12)),
                ('year', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['phone_number'],
                'db_table': 'vmycarsfilterdrivermonthyear',
                'managed': False,
                'verbose_name_plural': 'Uber Driver Filter',
            },
        ),
    ]
