# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='city',
            field=models.CharField(default=0, max_length=20, verbose_name='ciudad'),
        ),
        migrations.AddField(
            model_name='driver',
            name='country',
            field=models.CharField(default='M\xe9xico', max_length=20, verbose_name='pais'),
        ),
        migrations.AddField(
            model_name='driver',
            name='curp',
            field=models.CharField(default=0, max_length=18, verbose_name='apellidos'),
        ),
        migrations.AddField(
            model_name='driver',
            name='email',
            field=models.CharField(default='', max_length=120, verbose_name='apellidos'),
        ),
        migrations.AddField(
            model_name='driver',
            name='ext_number',
            field=models.CharField(default=0, max_length=20, verbose_name='n\xfamero exterior'),
        ),
        migrations.AddField(
            model_name='driver',
            name='ife_number',
            field=models.CharField(default=0, max_length=20, verbose_name='apellidos'),
        ),
        migrations.AddField(
            model_name='driver',
            name='int_number',
            field=models.CharField(default=0, max_length=20, verbose_name='numero interior'),
        ),
        migrations.AddField(
            model_name='driver',
            name='state',
            field=models.CharField(choices=[('0', 'Seleccione el estado'), ('1', 'Aguascalientes     '), ('2', 'Baja California    '), ('3', 'Baja California Sur'), ('4', 'Campeche           '), ('5', 'Chiapas            '), ('6', 'Chihuahua          '), ('7', 'Ciudad de M\xe9xico   '), ('8', 'Coahuila           '), ('9', 'Colima             '), ('10', 'Durango          '), ('11', 'Estado de M\xe9xico '), ('12', 'Guanajuato       '), ('13', 'Guerrero         '), ('14', 'Hidalgo          '), ('15', 'Jalisco          '), ('16', 'Michoac\xe1n        '), ('17', 'Morelos          '), ('18', 'Nayarit          '), ('19', 'Nuevo Le\xf3n       '), ('20', 'Oaxaca           '), ('21', 'Puebla           '), ('22', 'Quer\xe9taro        '), ('23', 'Quintana Roo     '), ('24', 'San Luis Potos\xed  '), ('25', 'Sin Localidad    '), ('26', 'Sinaloa          '), ('27', 'Sonora           '), ('28', 'Tabasco          '), ('29', 'Tamaulipas       '), ('30', 'Tlaxcala         '), ('31', 'Veracruz         '), ('32', 'Yucat\xe1n          '), ('33', 'Zacatecas        ')], default=0, max_length=2, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='driver',
            name='street',
            field=models.CharField(default='', max_length=20, verbose_name='calle'),
        ),
        migrations.AddField(
            model_name='driver',
            name='zip_code',
            field=models.CharField(default=0, max_length=5, verbose_name='codigo postal'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='blod_type',
            field=models.CharField(choices=[('0', 'Seleccione el tipo de sangre'), ('1', 'O-'), ('2', 'O+'), ('3', 'A-'), ('4', 'A+'), ('5', 'B-'), ('6', 'B+'), ('7', 'AB-'), ('8', 'AB+')], default=0, max_length=1, verbose_name='tipo de sangre'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_type',
            field=models.CharField(choices=[('0', 'Tipo de licencia'), ('A', 'TIPO A '), ('B', 'TIPO B'), ('C', 'TIPO C'), ('D', 'TIPO D')], default=0, max_length=1, verbose_name='tipo de licencia'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('0', 'N/A'), ('1', 'activo'), ('2', 'inactivo')], default=0, max_length=1, verbose_name='status del chofer'),
        ),
    ]
