# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_auto_20170103_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='license_photo_back',
            field=models.ImageField(default='', upload_to='media/drivers'),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_photo_front',
            field=models.ImageField(default='', upload_to='media/drivers'),
        ),
    ]
