# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_auto_20170111_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='photo',
            field=models.ImageField(default='', upload_to='drivers/', verbose_name='Foto chofer:'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_photo_back',
            field=models.ImageField(blank=True, default='', upload_to='drivers/license', verbose_name='Foto licencia reverso'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_photo_front',
            field=models.ImageField(blank=True, default='', upload_to='drivers/licence', verbose_name='Foto licencia frente'),
        ),
    ]
