# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 02:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_auto_20170111_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='ultima modificacion'),
        ),
        migrations.AddField(
            model_name='driver',
            name='phone',
            field=models.CharField(default='', max_length=10, verbose_name='celular'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='birthdate',
            field=models.DateField(default=datetime.datetime.now, verbose_name='fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de alta'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='photo',
            field=models.ImageField(default='', upload_to='drivers/', verbose_name='foto chofer:'),
        ),
    ]
