# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0006_auto_20170112_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='email'),
        ),
    ]
