# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0008_auto_20170112_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
    ]
