# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0009_auto_20170112_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='gender',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femanino')], default=0, max_length=9, verbose_name='genero'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='blod_type',
            field=models.CharField(choices=[('0', 'Seleccione el tipo de sangre'), ('O-', 'O-'), ('O+', 'O+'), ('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+')], default=0, max_length=3, verbose_name='tipo de sangre'),
        ),
    ]
