# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0010_auto_20170112_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='street',
            field=models.CharField(default='', max_length=150, verbose_name='calle'),
        ),
    ]
