# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 03:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0011_auto_20170112_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='int_number',
        ),
        migrations.AlterField(
            model_name='driver',
            name='blod_type',
            field=models.CharField(blank=True, choices=[('0', 'Seleccione el tipo de sangre'), ('O-', 'O-'), ('O+', 'O+'), ('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+')], default=0, max_length=3, verbose_name='tipo de sangre'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='city',
            field=models.CharField(blank=True, default=0, max_length=20, verbose_name='ciudad'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='country',
            field=models.CharField(blank=True, default='M\xe9xico', max_length=20, verbose_name='pais'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='curp',
            field=models.CharField(blank=True, default=0, max_length=18, verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='ext_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='n\xfamero exterior'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='ife_number',
            field=models.CharField(blank=True, default=0, max_length=20, verbose_name='IFE'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='numero de licencia'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_type',
            field=models.CharField(blank=True, choices=[('0', 'Tipo de licencia'), ('A', 'TIPO A '), ('B', 'TIPO B'), ('C', 'TIPO C'), ('D', 'TIPO D')], default=0, max_length=1, verbose_name='tipo de licencia'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_valid',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='fecha de vencimiento'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='state',
            field=models.CharField(blank=True, choices=[('0', 'Seleccione el estado'), ('1', 'Aguascalientes     '), ('2', 'Baja California    '), ('3', 'Baja California Sur'), ('4', 'Campeche           '), ('5', 'Chiapas            '), ('6', 'Chihuahua          '), ('7', 'Ciudad de M\xe9xico   '), ('8', 'Coahuila           '), ('9', 'Colima             '), ('10', 'Durango          '), ('11', 'Estado de M\xe9xico '), ('12', 'Guanajuato       '), ('13', 'Guerrero         '), ('14', 'Hidalgo          '), ('15', 'Jalisco          '), ('16', 'Michoac\xe1n        '), ('17', 'Morelos          '), ('18', 'Nayarit          '), ('19', 'Nuevo Le\xf3n       '), ('20', 'Oaxaca           '), ('21', 'Puebla           '), ('22', 'Quer\xe9taro        '), ('23', 'Quintana Roo     '), ('24', 'San Luis Potos\xed  '), ('25', 'Sin Localidad    '), ('26', 'Sinaloa          '), ('27', 'Sonora           '), ('28', 'Tabasco          '), ('29', 'Tamaulipas       '), ('30', 'Tlaxcala         '), ('31', 'Veracruz         '), ('32', 'Yucat\xe1n          '), ('33', 'Zacatecas        ')], default=0, max_length=2, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='street',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='calle'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='codigo postal'),
        ),
    ]
