# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0013_driver_int_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(default='', max_length=10, unique=True, verbose_name='celular'),
        ),
    ]
