# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0014_auto_20170112_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(default='', max_length=11, unique=True, verbose_name='celular'),
        ),
    ]
