# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-13 05:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0015_auto_20170112_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['last_name', 'name'], 'verbose_name_plural': 'choferes'},
        ),
    ]
