# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 04:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurances', '0005_policy_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='marca')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='fecha de alta')),
            ],
            options={
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=20, verbose_name='modelo')),
                ('make_year', models.CharField(choices=[('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026')], default=0, max_length=2, verbose_name='a\xf1o de fabricacion')),
                ('plate', models.CharField(max_length=10, verbose_name='placa')),
                ('passengers', models.IntegerField(default=4, verbose_name='pasajeros')),
                ('uber_number', models.CharField(max_length=20, verbose_name='numero en UBER')),
                ('color', models.CharField(max_length=20, verbose_name='color')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='fecha de alta')),
                ('cylinders', models.IntegerField(default=4, verbose_name='cilindros')),
                ('fuel_type', models.CharField(choices=[('0', 'Selecciona el tipo de gasolina'), ('1', 'Magna'), ('2', 'Premium'), ('2', 'Disel')], default=0, max_length=2, verbose_name='tipo de combustible')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='vehicle.Brand', verbose_name='marca')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='insurances.Policy', verbose_name='poliza')),
            ],
            options={
                'verbose_name_plural': 'Vehiculos',
            },
        ),
    ]
