# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_auto_20170109_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='ultima modificacion'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='ultima modificacion'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de alta'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de alta'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('0', 'Selecciona el tipo de gasolina'), ('Magna', 'Magna'), ('Premium', 'Premium'), ('Disel', 'Disel')], default=0, max_length=2, verbose_name='tipo de combustible'),
        ),
    ]
