# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_auto_20170112_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('0', 'Selecciona el tipo de gasolina'), ('Magna', 'Magna'), ('Premium', 'Premium'), ('Disel', 'Disel')], default=0, max_length=7, verbose_name='tipo de combustible'),
        ),
    ]
