# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-13 03:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0015_auto_20170112_2209'),
        ('vehicle', '0004_auto_20170112_0347'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleAssigment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='inicio de la asignacion')),
                ('initial_odo', models.FloatField(default=0, verbose_name='kilometraje inicial')),
                ('end_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='fin de la asignacion')),
                ('final_odo', models.FloatField(default=0, verbose_name='kilometraje final')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de alta')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='ultima modificacion')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicleassigment', to='drivers.Driver', verbose_name='chofer')),
            ],
            options={
                'verbose_name_plural': 'Asignaciones de Vehiculo',
            },
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='uber_number',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(max_length=10, unique=True, verbose_name='placa'),
        ),
        migrations.AddField(
            model_name='vehicleassigment',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vehicle', to='vehicle.Vehicle', verbose_name='vehiculo'),
        ),
    ]
