# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-13 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_auto_20170113_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='serial_number',
            field=models.CharField(default=0, max_length=30, unique=True, verbose_name='numero de serie'),
        ),
    ]
