# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-13 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_vehicle_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(max_length=10, verbose_name='placa'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='serial_number',
            field=models.CharField(default=0, max_length=30, verbose_name='numero de serie'),
        ),
    ]
