# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-13 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0007_auto_20170113_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(max_length=10, unique=True, verbose_name='placa'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='serial_number',
            field=models.CharField(default=0, max_length=30, unique=True, verbose_name='numero de serie'),
        ),
    ]
