# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0015_auto_20170116_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radio', models.NullBooleanField(verbose_name='radio')),
                ('flor_mats', models.NullBooleanField(verbose_name='tapetes')),
                ('lighter', models.NullBooleanField(verbose_name='eencendedor')),
                ('extinguisher', models.NullBooleanField(verbose_name='extinguidor')),
                ('hydraulic_jack', models.NullBooleanField(verbose_name='gato')),
                ('tools', models.NullBooleanField(verbose_name='herramientas')),
                ('wheel_brace', models.NullBooleanField(verbose_name='llave de cruz')),
                ('spare_tire', models.NullBooleanField(verbose_name='llanta de refaccion')),
                ('oil_cap', models.NullBooleanField(verbose_name='tapon de aceite')),
                ('radiator_cap', models.NullBooleanField(verbose_name='tapon de radiador')),
                ('dipstick', models.NullBooleanField(verbose_name='varilla de aceite')),
                ('antenna', models.NullBooleanField(verbose_name='antena')),
                ('mirrors', models.NullBooleanField(verbose_name='espejos')),
                ('crystals', models.NullBooleanField(verbose_name='cristales')),
                ('wheel_covers', models.NullBooleanField(verbose_name='tapones')),
                ('gas_cap', models.NullBooleanField(verbose_name='tapon de gasolina')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenceserviceorder', to='vehicle.Vehicle', verbose_name='vehiculo')),
            ],
        ),
    ]
