# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 01:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='fecha de alta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='fecha de elaboracion'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='delivery',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='fecha de entrega'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='ultima modificacion'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='reception',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='fecha de entrada'),
        ),
    ]
