# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 01:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_auto_20170127_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='delivery',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='fecha de entrega'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='reception',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='fecha de entrada'),
        ),
    ]
