# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 02:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_auto_20170127_0146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceorder',
            old_name='flor_mats',
            new_name='floor_mats',
        ),
    ]
