# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 02:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_auto_20170127_0204'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceConcept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=10, unique=True, verbose_name='concepto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de alta')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='ultima modificacion')),
            ],
            options={
                'verbose_name_plural': 'concepto del servicio',
            },
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='delivery',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='fecha de entrega del vehiculo'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='reception',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='fecha de entrada del vehiculo'),
        ),
    ]
