# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_auto_20170127_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceconcept',
            name='concept',
            field=models.CharField(max_length=50, unique=True, verbose_name='concepto'),
        ),
    ]
