# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_auto_20170127_0247'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='descripcion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de alta')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='ultima modificacion')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ServiceItem', to='maintenance.ServiceConcept', verbose_name='concepto')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'descripcion del trabajo',
            },
        ),
    ]
