# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 03:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0009_auto_20170127_0302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceitem',
            options={'ordering': ['concept', 'name'], 'verbose_name_plural': 'descripcion del trabajo'},
        ),
    ]
