# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 03:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0012_auto_20170127_0342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceitemprice',
            options={'verbose_name_plural': 'importe del trabajo'},
        ),
    ]
