# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 04:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0015_auto_20170127_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='serviceitemprice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.ServiceItemPrice', verbose_name='reparacion'),
        ),
    ]
