# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0021_serviceorder_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spare_parts', models.FloatField(default=0, verbose_name='precio refacciones')),
                ('workforce', models.FloatField(default=0, verbose_name='mano de obra')),
            ],
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='serviceitemprice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.Price', verbose_name='reparacion'),
        ),
    ]
