# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0022_auto_20170127_0501'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrderPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spare_parts', models.FloatField(default=0, verbose_name='precio refacciones')),
                ('workforce', models.FloatField(default=0, verbose_name='mano de obra')),
            ],
        ),
        migrations.RemoveField(
            model_name='serviceitemprice',
            name='service_item',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='serviceitemprice',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.DeleteModel(
            name='ServiceItemPrice',
        ),
        migrations.AddField(
            model_name='serviceorderprice',
            name='service_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.ServiceOrder'),
        ),
    ]
