# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 05:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0024_auto_20170127_0523'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceOrder',
            new_name='ServiceOrderDetail',
        ),
        migrations.RenameModel(
            old_name='ServiceOrderPrice',
            new_name='ServiceOrderTotal',
        ),
    ]
