# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 05:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0025_auto_20170127_0534'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceOrderDetail',
            new_name='ServiceOrder',
        ),
        migrations.RenameModel(
            old_name='ServiceOrderTotal',
            new_name='ServiceOrderPrice',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RenameField(
            model_name='serviceorderprice',
            old_name='service_order_item',
            new_name='service_item_price',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
