# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0026_auto_20170127_0541'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrderTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_item_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.ServiceItemPrice', verbose_name='Descripcion del trabajo')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.ServiceOrder')),
            ],
            options={
                'verbose_name_plural': 'Trabajos Realizados',
            },
        ),
        migrations.RemoveField(
            model_name='serviceorderprice',
            name='service_item_price',
        ),
        migrations.RemoveField(
            model_name='serviceorderprice',
            name='service_order',
        ),
        migrations.DeleteModel(
            name='ServiceOrderPrice',
        ),
    ]
