# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0027_auto_20170127_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceordertotal',
            name='service_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.ServiceOrder', verbose_name='Orden de Servicio'),
        ),
    ]
