# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0030_auto_20170202_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceitemprice',
            name='spare_parts',
        ),
        migrations.RemoveField(
            model_name='serviceitemprice',
            name='workforce',
        ),
        migrations.AddField(
            model_name='serviceordertotal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='fecha de alta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceordertotal',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='ultima modificacion'),
        ),
    ]
