# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 04:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0032_auto_20170202_0232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceordertotal',
            old_name='service_item_price',
            new_name='service_item',
        ),
    ]
