# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0033_auto_20170202_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceordertotal',
            name='item_total',
            field=models.FloatField(default=0, verbose_name='total'),
        ),
    ]
