# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0034_serviceordertotal_item_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='comments',
            field=models.TextField(blank=True, default='', verbose_name='observaciones'),
        ),
    ]
